# -*- coding: utf-8 -*-
"""Section 1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11n3zzGu34AZp9EkUScs_1N7rDwMwYVH4

**Definition**

Time series: a series of data points indexed in time order.

<br/> 


 

Classically, there are two main approaches (not mutually exclusive) in time series analysis:



*   Time domain approach: focus on investigation of lagged relationships (e.g., how does what happened today affect what will happen tomorrow)


*   Frequency domain approach: focus on investigation of cycles (e.g., what is the economic cycle through periods of expansion and recession).


We will mainly address time domain approach in the course.

# 1.1 The Nature of Time Series Data
"""

install.packages("astsa");library(astsa) #install and load package

"""**Example**  Johnson & Johnson Quarterly Earnings"""

jj

class(jj)
typeof(jj)

plot(jj, type="o", ylab="Quarterly Earnings per Share")

"""**Note**: there is no data between discrete time points. 
People usually   connect the values at adjacent time periods to
reconstruct visually a hypothetical continuously evolving time series.

Observations: 
*   Trend
*   Cycle

Questions we can ask:


*   Predict next quarter earning.
*   Find external factors that explain earning fluctuation


...

**Example** Global Warming

The data are the
global mean land–ocean temperature index from 1880 to 2015, with the base period
1951-1980. In particular, the data are deviations, measured in degrees centigrade,
from the 1951-1980 average.
"""

globtemp

plot(globtemp, type="o", ylab="Global Temperature Deviations")

"""Observations



*   Irregular (random) fluctuation
*   Potential trend?

Questions we can ask:


*   Is there a breakpoint (or multiple ones) in the trend? $\Rightarrow$ Global warming?


(Topic: [Change Point Detection](https://en.wikipedia.org/wiki/Change_detection)).

...

**Example**: Speech Signal

100ms-frequency  sample of recorded speech for
the phrase   aaa $\cdots$ hhh.
"""

speech

plot(speech)

"""Observations



*   Regular repetition of cycles (*pitch periods*).
*   Amplitude changes over time while cyclic pattern is relatively stable.

Questions we can ask:



*   How can one recognize pattern in frequency domain?

(Topic: [Spectral Analysis](https://en.wikipedia.org/wiki/Spectral_analysis))

<br>

Our course will NOT go deep into analysis of regular cyclic time series (specially the ones with large-sample  and high-frequency). E.g., electric/sound/light signals. 

Refer to the subject [Signal Processesing](https://en.wikipedia.org/wiki/Signal_processing)



<br>

Statistical time series analysis emphasizes on analysis of time series *exhibiting irregular fluctuations* (in general, statistics is a subject dealing with noisy data).
"""

spec.pgram(speech) # wait until Chapter 4 to see

"""**Example**: Dow Jones Industrial Average


"""

install.packages("xts");library(xts)

head(djia,10) # first 10 rows of data
plot(djia$Close)

"""Suppose $x_t$ is the closing price at $t$th day.

However, people are usually more interested in the relative price change:

$\tilde{r}_t= \frac{x_t-x_{t-1}}{x_{t-1}}$.

In finance, people also look at a quantity called *log return*:

$r_t=\log(x_t/x_{t-1})=\log(x_t)-\log(x_{t-1})=\log\left(1+ \frac{x_t-x_{t-1}}{x_{t-1}} \right)\approx \tilde{r}_t$.

Fact: $\log(1+y)\approx y$ when $|y|$ is small.

"""

curve(log(1+x),-0.2,0.2) #plot log(1+x) function
abline(h=0, v=0)#plot x-y axes

"""**Definition**  The operation $(x_1,x_2,\ldots,x_n)\rightarrow (x_{\ell+1}-x_{1}, x_{\ell+2}-x_2,\ldots, x_{n}-x_{n-\ell+1})$ is called differencing, where $\ell=1,2,3,\ldots$ is called the *lag*. We take the lag $\ell=1$ by default if not specified otherwise.
 
In R it can be achieved with [diff](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/ts-methods) function.
"""

x<-c(1,3,5,7,9)
(diff(x))
(y<-diff(x,lag=2))

"""We first plot the log-transformed closing price."""

plot(djial<-log(djia$Close))

"""Log return can be obtained by first take log elementwise and then perform  differencing (lag=1)."""

djiar = diff(as.ts(djial))  #log return
plot(djiar, main="DJIA Returns")

"""Observations



*  Clustering of fluctuation magnitude (volatility clustering)
   


"""

par(mfrow = c(2,1)) # set up the graphics
acf(djiar) # compute & plot sample auto-correlation function (will elaborate later)
acf(abs(djiar))

"""Check "GARCH" models.

**Example** El Niño and Fish Population 

Monthly values of an environmental series called the Southern Oscillation
Index (*SOI*, changes in air pressure) and associated *Recruitment* (number of new fish)
"""

par(mfrow = c(2,1))  
plot(soi, ylab="", xlab="", main="Southern Oscillation Index")
plot(rec, ylab="", xlab="", main="Recruitment")

"""Observations


*    Both  collected at the same time points.
*    Annual cycle and   4-year cycle.
*    Two series are related.

Questions we can ask:


*   Are the cycles changing over time?
*   Joint analysis of two time series. E.g., do  SOI and Recruitment have a causal relationship?  

Time-Frequency Analysis (e.g., [Wavelet](https://en.wikipedia.org/wiki/Wavelet))

Causal analysis (e.g., [Granger Causality](https://en.wikipedia.org/wiki/Granger_causality))

Exercise 6. Plot multiple time series in a single graph.
"""